// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdH3vm9tdQzbjcG53sbs5O0-z7TReRTcY',
    appId: '1:580111714111:web:18609ddf1cc7532f46f58a',
    messagingSenderId: '580111714111',
    projectId: 'fastevergo',
    authDomain: 'fastevergo.firebaseapp.com',
    storageBucket: 'fastevergo.firebasestorage.app',
    measurementId: 'G-9GPWKM26JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDorPLBJEcKeZLVdOqVWgZnKT2MtYQdZoM',
    appId: '1:580111714111:android:83e1657ce667980d46f58a',
    messagingSenderId: '580111714111',
    projectId: 'fastevergo',
    storageBucket: 'fastevergo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjknIZg2k-KcROzTPjjnV_2yQTXJgTTH4',
    appId: '1:580111714111:ios:3b1c2afd15c1f10046f58a',
    messagingSenderId: '580111714111',
    projectId: 'fastevergo',
    storageBucket: 'fastevergo.firebasestorage.app',
    iosBundleId: 'com.example.fastevergoV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjknIZg2k-KcROzTPjjnV_2yQTXJgTTH4',
    appId: '1:580111714111:ios:3b1c2afd15c1f10046f58a',
    messagingSenderId: '580111714111',
    projectId: 'fastevergo',
    storageBucket: 'fastevergo.firebasestorage.app',
    iosBundleId: 'com.example.fastevergoV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdH3vm9tdQzbjcG53sbs5O0-z7TReRTcY',
    appId: '1:580111714111:web:4ff8942e4f55266c46f58a',
    messagingSenderId: '580111714111',
    projectId: 'fastevergo',
    authDomain: 'fastevergo.firebaseapp.com',
    storageBucket: 'fastevergo.firebasestorage.app',
    measurementId: 'G-DBXGB6EKR6',
  );
}
